version: 2
registries:
  docker-registry-registry-hub-docker-com:
    type: docker-registry
    url: https://registry.hub.docker.com
    username: arwynfr
    password: "${{secrets.DOCKER_REGISTRY_REGISTRY_HUB_DOCKER_COM_PASSWORD}}"

updates:
- package-ecosystem: docker
  directory: "/images/debian-10.0-slim"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: debian
    versions:
    - 10.7.pre.slim
    - 10.8.pre.slim
  registries:
  - docker-registry-registry-hub-docker-com
- package-ecosystem: docker
  directory: "/images/alpine-3.10.2"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: alpine
    versions:
    - 3.13.1
    - 3.13.2
    - 3.13.3
    - 3.13.4
  registries:
  - docker-registry-registry-hub-docker-com
