[package]
name = "armake2"
version = "0.1.0"
authors = ["KoffeinFlummi <koffeinflummi@protonmail.com>"]
build = "build.rs"

[dependencies]
time = "0.1"
docopt = "1"
serde = "1.0"
serde_derive = "1.0"

[build-dependencies]
peg = "0.5"
