[package]
name = "armake2"
version = "0.1.0"
description = "Arma 3 modding tools"
license = "GPL-2.0-or-later"
categories = ["command-line-utilities"]
authors = ["KoffeinFlummi <koffeinflummi@protonmail.com>"]
homepage = "https://github.com/KoffeinFlummi/armake2"
repository = "https://github.com/KoffeinFlummi/armake2"
build = "build.rs"
readme = "README.md"

[lib]
name = "armake2"

[dependencies]
colored = "1.6"
time = "0.1"
byteorder = "1"
docopt = "1"
serde = "1.0"
serde_derive = "1.0"
openssl = "0.10"
linked-hash-map = "0.5.1"
regex = "1"

[target.'cfg(windows)'.dependencies]
winreg = "0.6.0"

[build-dependencies]
peg = "0.5"
